source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'EventHub_Tests' do
    pod "EventHub", :path => "../"

    pod 'Quick'
    pod 'Nimble'
end

# cf. http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift-issue
post_install do |installer|
    swift5_names = [
    'Nimble',
    'Quick'
    ]

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if swift5_names.include? target.name
                config.build_settings['SWIFT_VERSION'] = '5.0'
            else
                config.build_settings['SWIFT_VERSION'] = '5.3'
            end
        end
    end
end
